### ISSUE TITLE
Доработать сборщик данных так, чтобы он собирал ссылку на полный текст новости и описание

### ISSUE THREAD

**Issue by fireSparrow** [Chefoxee/news_reader#2]
Надо доработать классы Item и RssFeed так, чтобы наш код забирал из источника ссылку на полный текст новости, и её описание (то есть link и description)

**Comment by Chefoxee** [comment]
Сделал проверь пжлст

**Comment by fireSparrow** [comment]
Не вижу никаких пулл реквестов. Проверь, что ты всё правильно запушил.
@Chefoxee

**Comment by fireSparrow** [comment]
А, увидел, ты его прямо в мастер закоммитил.
Лучше так не делать, потому что вдруг я какую-нибудь проблему увижу, а она уже в мастере.

**Comment by fireSparrow** [comment]
Выглядит ок, только на 22 строке зачем-то решётка добавилась )
